### ISSUE TITLE
pip install celi-framework + python -m celi_framework.main does not work

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#25]
Environment = Latest Anaconda environment with Python 3.11.8 (upon conda create with python=3.11)

pip install celi-framework

create .env from example from README to current directory - with OPENAI_API_KEY specified

python -m celi_framework.main 

2024-04-18 20:36:26,301 __main__ DEBUG - Starting CELI
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/main.py", line 150, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/main.py", line 112, in get_config
    job_description = get_obj_by_name(args.job_description)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/utils/utils.py", line 52, in get_obj_by_name
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/examples/wikipedia/job_description.py", line 3, in <module>
    from celi_framework.examples.wikipedia.tools import WikipediaToolImplementations
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/examples/wikipedia/tools.py", line 18, in <module>
    from celi_framework.examples.wikipedia.index import get_wikipedia_index
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/examples/wikipedia/index.py", line 33, in <module>
    from celi_framework.examples.wikipedia.caching_beautiful_soup_reader import (
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/examples/wikipedia/caching_beautiful_soup_reader.py", line 16, in <module>
    from pytest import Session
ModuleNotFoundError: No module named 'pytest'

pip install pytest

Successfully installed iniconfig-2.0.0 pluggy-1.4.0 pytest-8.1.1

python -m celi_framework.main

2024-04-18 20:37:23,156 __main__ DEBUG - Starting CELI
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/main.py", line 150, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/main.py", line 113, in get_config
    tool_config = read_json_from_file(args.tool_config_json)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-main-test/lib/python3.11/site-packages/celi_framework/utils/utils.py", line 711, in read_json_from_file
    with open(file_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by DaveDeCaprio** [comment]
@x3n0cr4735 Can you confirm you are using 0.0.14 or newer?  That line where the error is listed doesn't exist anymore in main:
https://github.com/x3n0cr4735/celi/blob/c32ee03a677b4630765f73c41aabf319ecae1832/celi_framework/examples/wikipedia/caching_beautiful_soup_reader.py#L12

**Comment by x3n0cr4735** [comment]
Tried again with a fresh anaconda env. 

python -m celi_framework.main
2024-04-19 13:58:42,529 __main__ DEBUG - Starting CELI
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-0.0.15/lib/python3.11/site-packages/celi_framework/main.py", line 164, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-0.0.15/lib/python3.11/site-packages/celi_framework/main.py", line 116, in get_config
    if os.path.exists(args.tool_config_json):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by x3n0cr4735** [comment]
This had the fixed .env with celi_framework instead of celi-framework for the path for tool config.

**Comment by DaveDeCaprio** [comment]
So I think the only way you can get that error is if you don't have a TOOL_CONFIG_JSON in your .env file.

I made the following PR:
Created https://github.com/x3n0cr4735/celi/pull/29 to resolve

This automatically deletes the cache if it fails during creation, which should eliminate the original issue going forward.
I also made TOOL_CONFIG_JSON optional if you don't have any config.  However, running the wikipedia example will still fail if you don't pass this in, as it is required for that use case.
