### ISSUE TITLE
0.0.18 has same issue as before 

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#37]
(celi-0.0.18) jwag@Jan-Samuels-MacBook-Pro test_celi % python -m celi_framework.main
2024-04-21 10:10:58,848 __main__ DEBUG - Starting CELI
2024-04-21 10:10:58,848 __main__ INFO - Tool config env. var is <not set>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jwag/anaconda3/envs/celi-0.0.18/lib/python3.11/site-packages/celi_framework/main.py", line 167, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/jwag/anaconda3/envs/celi-0.0.18/lib/python3.11/site-packages/celi_framework/main.py", line 132, in get_config
    tool_implementations = job_description.tool_implementations_class(**tool_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WikipediaToolImplementations.__init__() missing 2 required positional arguments: 'example_url' and 'target_url'

**Comment by DaveDeCaprio** [comment]
It's better to keep this as 1 issue that isn't resolved rather than making new issues.
I'll need to spend time later today to be able to reproduce this on my machine because load_dotenv keeps just working on my system.  My wife has a mac I can try that one.

**Comment by x3n0cr4735** [comment]
Sorry, working on mobile and unable to unmark as resolved

**Comment by x3n0cr4735** [comment]
That works, I'll approve code reviews and then you can just merge, deploy and test off pip install.

**Comment by DaveDeCaprio** [comment]
I was able to reproduce on my machine and fix.  New PR is up.  Try testing that again full.

 

Dave
