### ISSUE TITLE
running wikipedia example exits early

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#45]
mac os x, pip install from pypi

Exception in thread Thread-2 (run):
Traceback (most recent call last):
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mkmz/Documents/GitHub/celi/celi_framework/core/processor.py", line 660, in run
    self.process_iteration2()
  File "/Users/mkmz/Documents/GitHub/celi/celi_framework/core/processor.py", line 207, in process_iteration2
    self.update_draft_doc(self.ongoing_chat)
  File "/Users/mkmz/Documents/GitHub/celi/celi_framework/core/processor.py", line 219, in update_draft_doc
    parsed_draft = parse(
  File "/Users/mkmz/Documents/GitHub/celi/celi_framework/utils/llmcore_utils.py", line 217, in parse
    raise e
  File "/Users/mkmz/Documents/GitHub/celi/celi_framework/utils/llmcore_utils.py", line 206, in parse
    ret = parser.parse(msg)  # type: ignore
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/llm_core/parsers.py", line 23, in parse
    instance = self.deserialize(completion.choices[0].message.content)
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/llm_core/parsers.py", line 14, in deserialize
    attributes = dirtyjson.loads(json_str)
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/dirtyjson/__init__.py", line 94, in loads
    return d.decode(search_for_first_object, start_index)
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/dirtyjson/loader.py", line 372, in decode
    obj = self.scan()
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/dirtyjson/loader.py", line 173, in scan
    return self.parse_object()
  File "/opt/anaconda3/envs/celi_env_conda/lib/python3.10/site-packages/dirtyjson/loader.py", line 325, in parse_object
    raise Error("Expecting ',' delimiter or '}'", self.content, self.pos - len(nextchar))
dirtyjson.error.Error: Expecting ',' delimiter or '}': line 3 column 3404 (char 3427)
2024-04-24 15:59:47,568 app_logger INFO - Threads completed. Exiting.

**Comment by x3n0cr4735** [comment]
hey @MarkAMartinez please add anything i missed here

**Comment by DaveDeCaprio** [comment]
This appears to be indeterministic behavior.  It's failing because the LLM is returning bad JSON.

I added in some error handling in my fix PR.  That should resolve it, but I couldn't reproduce to test.
