### ISSUE TITLE
cannot get through example

### ISSUE THREAD

**Issue by verikono** [x3n0cr4735/celi#50]
I've tried both Debian and Ubuntu on Windows11/WSL2 and with either freshly installed WSL2 container I cannot - for the life of me - get through the example.

***Steps:***

Spin up a fresh WSL2 Ubuntu or Debian environment on windows 11.

**Install Python**
```bash
sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update && sudo apt install python3.11
```

**Install Docker**
  In WSL2 docker is exposed to the container by a HOST installation, so install Docker Desktop and enable WSL2 integration in the options. Nothing special here.

**Provide a Mongo container**
```bash
docker run --name mongodb -p 27017:27017 -d mongo
```

**Clone the repo**
```bash
git clone git@github.com:verikono/celi.git ~/celi
```

**Step into the repo and edit the .env file**
```bash
cd ~/celi && cp .env.example .env && vim .env
```
... apply your openAI key and save.

**Create a virtual environment and activate it**
```bash
python3 -m venv .venv
activate .venv/bin/activate
```

**Install**
```bash
pip install -e .
```

**Test Installation**
```bash
python -m celi_framework.main
```

I get;

```
2024-04-29 10:16:46,858 __main__ DEBUG - Starting CELI
2024-04-29 10:16:46,858 __main__ INFO - Tool config env. var is celi_framework/examples/wikipedia/example_config.json
2024-04-29 10:16:47,704 celi_framework.examples.wikipedia.index DEBUG - Ignore updates is set to True.  Using existing cache entry for https://en.wikipedia.org/wiki/Led_Zeppelin.
2024-04-29 10:16:47,704 celi_framework.examples.wikipedia.Index_cache DEBUG - ChromaDB index for CR-1876773ababf33b8 is at /home/bren/.cache/celi/index/chroma_db/CR-1876773ababf33b8, created at 2024-04-26 22:56:37.902210+00:00
2024-04-29 10:16:47,707 chromadb.telemetry.product.posthog INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2024-04-29 10:16:47,755 celi_framework.examples.wikipedia.index INFO - Using cached index CR-1876773ababf33b8 for https://en.wikipedia.org/wiki/Led_Zeppelin.
2024-04-29 10:16:47,895 celi_framework.examples.wikipedia.index DEBUG - Ignore updates is set to True.  Using existing cache entry for https://en.wikipedia.org/wiki/Jonas_Brothers.
2024-04-29 10:16:47,896 celi_framework.examples.wikipedia.Index_cache DEBUG - ChromaDB index for R-77bfa7a7d14fc66f is at /home/bren/.cache/celi/index/chroma_db/R-77bfa7a7d14fc66f, created at 2024-04-26 22:57:34.252579+00:00
2024-04-29 10:16:47,897 chromadb.telemetry.product.posthog INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
2024-04-29 10:16:47,901 celi_framework.examples.wikipedia.index INFO - Using cached index R-77bfa7a7d14fc66f for https://en.wikipedia.org/wiki/Jonas_Brothers.
2024-04-29 10:16:47,926 app_logger DEBUG - Beginning document generation
2024-04-29 10:16:47,926 celi_framework.utils.codex INFO - Creating a new instance of MongoDBUtilitySingleton
2024-04-29 10:16:47,928 app_logger INFO - Sections (num) remaining after processing skip list: 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bren/celi/celi_framework/main.py", line 168, in <module>
    run_celi(config)
  File "/home/bren/celi/celi_framework/core/runner.py", line 67, in run_celi
    process_runner = ProcessRunner(
                     ^^^^^^^^^^^^^^
  File "/home/bren/celi/celi_framework/core/processor.py", line 165, in __init__
    self.current_section = self.sections_to_be_completed[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by violenz** [comment]
@x3n0cr4735  - hit me up sometime today, its probably me and if so we can close this.

**Comment by verikono** [comment]
Thanks! Will get a suitable key and try again :)
