### ISSUE TITLE
trouble with wikipedia eval

### ISSUE THREAD

**Issue by x3n0cr4735** [x3n0cr4735/celi#94]
(celi-framework) python -m celi_framework.examples.wikipedia.eval.run_eval
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/path/to/files/celi/celi_framework/examples/wikipedia/eval/run_eval.py", line 120, in <module>
    celi_config = get_config()
                  ^^^^^^^^^^^^
  File "/path/to/files/celi/celi_framework/examples/wikipedia/eval/run_eval.py", line 36, in get_config
    use_monitor = not args.no_monitor
                      ^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'no_monitor'

**Comment by DaveDeCaprio** [comment]
I'm not sure what branch you are on.  That error doesn't line up with the code on master.  run_eval doesn't have a get_config function at all anymore.

**Comment by DaveDeCaprio** [comment]
Main branch is running fine for me.
